/*reqToServer.js*/
export const REQ_TO_SERVER_START = 'REQ_TO_SERVER_START'
export const REQ_TO_SERVER_SUCCESS = 'REQ_TO_SERVER_SUCCESS'
export const REQ_TO_SERVER_FAIL = 'REQ_TO_SERVER_FAIL'
/*auth.js*/
export const AUTH_SUCCESS = 'AUTH_SUCCESS'
export const LOGOUT = 'LOGOUT'

/*burgerBuilder.js*/
export const ADD_INGREDIENT = 'ADD_INGREDIENT'
export const REMOVE_INGREDIENT = 'REMOVE_INGREDIENT'
export const SET_PRICES = 'SET_PRICES'
export const FETCH_PRICES_FAILED = 'FETCH_PRICES_FAILED'
/*order.js*/
export const PURCHASE_BURGER_FINISH = 'PURCHASE_BURGER_FINISH'
export const PURCHASE_BURGER_SUCCESS = 'PURCHASE_BURGER_SUCCESS'
export const FETCH_ORDERS_SUCCESS = 'FETCH_ORDERS_SUCCESS'

/*catalog.js*/
export const ADD_PRODUCT = 'ADD_PRODUCT'
export const REMOVE_PRODUCT = 'REMOVE_PRODUCT'
// export const SET_PRICES = 'SET_PRICES'
// export const FETCH_PRICES_FAILED = 'FETCH_PRICES_FAILED'

/*order.js*/
export const PURCHASE_BURGER_FINISH = 'PURCHASE_BURGER_FINISH'
export const PURCHASE_BURGER_SUCCESS = 'PURCHASE_BURGER_SUCCESS'
export const FETCH_ORDERS_SUCCESS = 'FETCH_ORDERS_SUCCESS'
